[tool.pytest.ini_options]
minversion = "6.0"
addopts = "--doctest-modules --doctest-report=ndiff"
console_output_style = "count"
filterwarnings = "ignore::DeprecationWarning"
junit_duration_report = "call"
